use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use tokio::fs;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScannerConfig {
    #[serde(default)]
    pub github_token: Option<String>,

    #[serde(default = "default_max_requests")]
    pub max_requests: usize,
    
    #[serde(default = "default_concurrency")]
    pub concurrency: usize,
    
    #[serde(default = "default_output_path")]
    pub output_path: String,
    
    #[serde(default)]
    pub scan_mode: ScanMode,
    
    #[serde(default)]
    pub custom_queries: Vec<String>,
    
    #[serde(default)]
    pub enable_validation: bool,
    
    #[serde(default)]
    pub enable_tui: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum ScanMode {
    TimeSlotted,
    FullScan,
    GoogleDorks,
    CustomQueries,
}

impl Default for ScanMode {
    fn default() -> Self {
        Self::TimeSlotted
    }
}

impl ScanMode {
    pub fn to_flags(&self) -> (bool, bool) {
        match self {
            ScanMode::GoogleDorks => (true, false),
            ScanMode::FullScan => (false, true),
            _ => (false, false),
        }
    }
    
    pub fn description(&self) -> &str {
        match self {
            ScanMode::TimeSlotted => "Time-slotted (1 query, fast)",
            ScanMode::FullScan => "Full scan (10 queries, comprehensive)",
            ScanMode::GoogleDorks => "Google Dorks (advanced patterns)",
            ScanMode::CustomQueries => "Custom queries (user-selected)",
        }
    }
}

fn default_max_requests() -> usize { 10 }
fn default_concurrency() -> usize { 5 }
fn default_output_path() -> String { "data".to_string() }

impl Default for ScannerConfig {
    fn default() -> Self {
        Self {
            github_token: None,
            max_requests: default_max_requests(),
            concurrency: default_concurrency(),
            output_path: default_output_path(),
            scan_mode: ScanMode::default(),
            custom_queries: Vec::new(),
            enable_validation: false,
            enable_tui: true,
        }
    }
}

impl ScannerConfig {
    pub fn config_path() -> PathBuf {
        PathBuf::from("scanner-config.toml")
    }
    
    pub async fn load() -> Result<Self> {
        let path = Self::config_path();
        
        if !path.exists() {
            return Ok(Self::default());
        }
        
        let content = fs::read_to_string(&path).await?;
        let config: Self = toml::from_str(&content)?;
        Ok(config)
    }
    
    pub async fn save(&self) -> Result<()> {
        let path = Self::config_path();
        let content = toml::to_string_pretty(self)?;
        fs::write(&path, content).await?;
        Ok(())
    }
    
    pub async fn exists() -> bool {
        Self::config_path().exists()
    }
    
    #[allow(dead_code)]
    pub fn to_toml_string(&self) -> Result<String> {
        Ok(toml::to_string_pretty(self)?)
    }
}

// Example config template
#[allow(dead_code)]
pub fn generate_example_config() -> String {
    r#"# API Key Scanner Configuration
# This file is automatically generated and can be edited manually

# Optional saved GitHub token for interactive runs
github_token = ""

# Maximum number of GitHub API requests per scan
max_requests = 10

# Number of concurrent repository scans
concurrency = 5

# Output directory for scan results
output_path = "data"

# Scan mode: "time_slotted", "full_scan", "google_dorks", or "custom_queries"
scan_mode = "time_slotted"

# Custom queries (only used when scan_mode = "custom_queries")
custom_queries = [
    "sk-proj- filename:.env",
    "OPENAI_API_KEY extension:env",
]

# Enable live API key validation after scan
enable_validation = false

# Enable TUI (Terminal User Interface) mode
enable_tui = true
"#.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_default_config() {
        let config = ScannerConfig::default();
        assert_eq!(config.max_requests, 10);
        assert_eq!(config.concurrency, 5);
        assert_eq!(config.scan_mode, ScanMode::TimeSlotted);
    }
    
    #[test]
    fn test_serialize_deserialize() {
        let config = ScannerConfig::default();
        let toml_str = config.to_toml_string().unwrap();
        let deserialized: ScannerConfig = toml::from_str(&toml_str).unwrap();
        assert_eq!(config.max_requests, deserialized.max_requests);
    }
}
